name: Build Windows Portable

on:
  workflow_dispatch:

permissions: {}

jobs:
  build-portable:
    runs-on: windows-2022
    env:
      PICARD_BUILD_PORTABLE: 1

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1000
        fetch-tags: true
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Setup Windows build environment
      run: |
        & .\scripts\package\win-setup.ps1 `
          -DiscidVersion $Env:DISCID_VERSION -DiscidSha256Sum $Env:DISCID_SHA256SUM `
          -FpcalcVersion $Env:FPCALC_VERSION -FpcalcSha256Sum $Env:FPCALC_SHA256SUM
      env:
        DISCID_VERSION: 0.6.5
        DISCID_SHA256SUM: a1198731d417a04b3d8499bcc10b6a8ddcab06476c855ebff0fb4134888b1be5
        FPCALC_VERSION: 1.6.0
        FPCALC_SHA256SUM: 30179d3d0dc4cc92f1a0995c1a2e523fb4867724c2ee6a6ceae474f8e4d6937a
    - name: Install gettext
      run: |
        & .\scripts\package\win-setup-gettext.ps1 `
          -GettextVersion $Env:GETTEXT_VERSION -GettextSha256Sum $Env:GETTEXT_SHA256SUM
        Add-Content $env:GITHUB_PATH (Join-Path -Path (Resolve-Path .) -ChildPath gettext\bin)
      env:
        GETTEXT_VERSION: 0.22.4
        GETTEXT_SHA256SUM: 220068ac0b9e7aedda03534a3088e584640ac1e639800b3a0baa9410aa6d012a
    - name: Install dependencies
      run: uv sync --group build --extra plugins
    - name: Patch build version
      run: uv run bash -c "./scripts/tools/patch-version.sh"
    - name: Run tests
      timeout-minutes: 30
      run: uv run pytest --verbose
    - name: Build
      run: |
        $ReleaseTag = $(git describe --match "release-*" --abbrev=0 --always HEAD)
        $BuildNumber = $(git rev-list --count "$ReleaseTag..HEAD")
        uv run python setup.py build --build-number=$BuildNumber --disable-locales
        uv run python setup.py build_locales
        uv run python setup.py build_ext -i
        uv run pyinstaller --noconfirm --clean picard.spec
    - name: Upload portable executable
      uses: actions/upload-artifact@v7
      with:
        name: picard-portable
        path: dist/*.exe
